steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=asia.gcr.io/$PROJECT_ID/node:latest"
      - "."
    waitFor: ["-"]

images:
  - "gcr.io/$PROJECT_ID/node:latest"
